kind: Service
apiVersion: v1
metadata:
   name: blue-deployment
   labels:
     name: blue-deployment
spec:
   selector:
     name: blue-deployment
   ports:
   - protocol: TCP 
     port: 8080   
     targetPort: 8080
   type: LoadBalancer
