kind: Service
apiVersion: v1
metadata:
   name: green-deployment
   labels:
     name: green-deployment
spec:
   selector:
     name: green-deployment
   ports:
   - protocol: TCP 
     port: 8080   
     targetPort: 8080
   type: LoadBalancer
