apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    app: my-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:    
      containers:
      - name: green
        image: ankushsatpute/ankush:tagVersion
        imagePullPolicy: Always      
        ports:
        - containerPort: 8080
