apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      name: blue-deployment
  template:
    metadata:
      labels:
        name: blue-deployment
    spec:    
      containers:
      - name: blue-deployment
        image: ankushsatpute/ankush:latest
        imagePullPolicy: Always      
        ports:
        - containerPort: 8080
